#Minecraft server properties
#Tue Apr 28 21:18:07 BRT 2026
allow-flight=false
allow-nether=true
level-name=world
level-seed=
max-players=5
online-mode=false
pvp=true
server-ip=
server-port=25565
spawn-animals=true
spawn-monsters=true
view-distance=15
white-list=false
